
name: Run tests

on:
  push:
    branches:
      - "master"


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x]
        mongodb-version: [ '6.0']
    
    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: arrimo_challenge_test
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5


    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      - name: Run Test
        uses: borales/actions-yarn@v4
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
        with:
          cmd: test


