
name: Run tests

on:
  push:
    branches:
      - "master"

env:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  DB_NAME_TEST: arrimo_challenge_test
  POSTGRES_PORT: 5432
  DB_HOST: localhost

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x]
        mongodb-version: [ '6.0']
    
    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: arrimo_challenge_test
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5


    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: 'Create env file'
              run: |
                touch .env
                echo POSTGRES_USER=${{ env.POSTGRES_USER }} >> .env
                echo POSTGRES_PASSWORD=${{ env.POSTGRES_PASSWORD }} >> .env
                echo DB_NAME_TEST=${{ env.DB_NAME_TEST }} >> .env
                echo POSTGRES_PORT=${{ env.POSTGRES_PORT }} >> .env
                echo DB_HOST=${{ env.DB_HOST }} >> .env
                cat .env
                
      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      - name: Run Test
        uses: borales/actions-yarn@v4
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
        with:
          cmd: test


